version: "3"
services:
  go:
    environment:
      - GO_ENV=production
    build:
      context: .
      dockerfile: ./dockerfiles/go.Dockerfile
    image: go
    container_name: go
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - pg
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/hc || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
  pg:
    container_name: pg
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - todo-app:/var/lib/postgresql/data/
      - ./migration.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      start_period: 5s
      retries: 5
volumes:
  todo-app:
