package constant

const (
	TASK_STATUS_ON_GOING = "on_going"
	TASK_STATUS_COMPLETED = "completed"
)

const (
	PAGE_SIZE_MIN = 1
	PAGE_SIZE_MAX = 20
	PAGE_SIZE_DEFAULT = 10
	PAGE_NUMBER_MIN = 1
	PAGE_NUMBER_MAX = 10
	PAGE_NUMBER_DEFAULT = 1
)